### ISSUE TITLE
gutentags fails while writing working copy with fugitive :Gdiff if index is modified

### ISSUE THREAD

**Issue by gauteh** [ludovicchabant/vim-gutentags#128] opened 2017-04-05 16:39 UTC
Hi, encountered a bit of a corner case: If I use :Gdiff (from fugitive) and I make some change to the index (left) (e.g. `dp` from working copy), then decide to modify something in the working copy (right) and write it to disk using `:w` without having written the index (left) I get the following error from gutentags:

```
Error detected while processing function <SNR>148_write_triggered_update_tags[3]..<SNR>148_update_tags[34]..gutentags#ctags#generate:
line 113:
"fugitive:///path/to/repo/.git//0/filename.ext" E212: Can't open file for writing
Error detected while processing function <SNR>148_write_triggered_update_tags:
line 3:
E170: Missing :endfor
```

**Comment by ludovicchabant** [comment] 2017-04-19 05:14
Hi!

I tried reproducing this but I wasn't able to.... the index buffer (left) was left edited, and Vim only asked me to save it when I discarded it (to which I said "no"). Maybe somehow you have something that auto-saved your edit?

**Comment by gauteh** [comment] 2017-04-19 07:40
Ludovic Chabant writes on april 19, 2017 7:14:
> Hi!
> 
> I tried reproducing this but I wasn't able to.... the index buffer (left) was left edited, and Vim only asked me to save it when I discarded it (to which I said "no"). Maybe somehow you have something that auto-saved your edit?

Hm, weird - that might be, I'll re-try on a few other repositories as
well.

Regards, Gaute

**Comment by arecarn** [comment] 2017-04-28 23:20
I've also encountered this issue. Looks like the setting `autowriteall` is what causes this auto saving.  I've hacked together this change that looks like it fixes the issue for me. 

```diff
diff --git a/autoload/gutentags.vim b/autoload/gutentags.vim
index 563eb5d..57575fd 100644
--- a/autoload/gutentags.vim
+++ b/autoload/gutentags.vim
@@ -270,7 +270,7 @@ function! gutentags#setup_gutentags() abort
     let l:bn = bufnr('%')
     execute 'augroup gutentags_buffer_' . l:bn
     execute '  autocmd!'
-    execute '  autocmd BufWritePost <buffer=' . l:bn . '> call s:write_triggered_update_tags(' . l:bn . ')'
+    execute '  autocmd BufWritePost <buffer=' . l:bn . '> if &bufhidden !=# "delete" | call s:write_triggered_update_tags(' . l:bn . ') | endif'
     execute 'augroup end'

     " Miscellaneous commands.
```

**Comment by arecarn** [comment] 2017-05-10 05:02
The buftype is normal but it looks like bufhidden is set to delete, so there could be a check for that, like I did in my hacky work around.

When you edit the index version you can selectively choose changes that you would like to stage and staging the file is what stages those changes, to be committed. It is sort of like improved git add --patch inside vim.

**Comment by gauteh** [comment] 2017-05-10 07:55
Does the bug happen with arbitrary buffers with bufhidden=delete set? If I understand correctly what this option does, it might be the correct behavior for gutentags to ignore it anyway?

**Comment by ludovicchabant** [comment] 2017-05-11 01:50
I wouldn't say Gutentags should generally ignore those, no... you could have `bufhidden=delete` on a buffer for some reason, and still edit it and go `:w` a few times, and you would expect the symbols to be indexed.

I wonder if the problem here is that `autowriteall` is writing the buffer on close, but `bufhidden=delete` is deleting it on close, and so it's trying to read a deleted buffer? I'll need to do more testing.

**Comment by gauteh** [comment] 2017-05-11 05:37
Ah right, yes.

**Comment by ludovicchabant** [comment] 2019-03-14 05:56
Closing old issues, and can't repro this anymore.

**Closed by ludovicchabant** 2019-03-14 05:56 UTC

**Comment by zoumi** [comment] 2020-12-08 08:19
I still get this bug, but I can't figure out how to trigger it. I use Vim every day, but it only occur a few times.
It disappears when I restart vim.
![error message](https://user-images.githubusercontent.com/5162901/101457756-dfdf3600-3970-11eb-9077-02525e89c829.png)

![gutentags version](https://user-images.githubusercontent.com/5162901/101457891-11580180-3971-11eb-853d-9a646d1ef939.png)
