### ISSUE TITLE
Gutentags is trying to generate ctags for Homebrew in /usr/local

### ISSUE THREAD

**Issue by emptyflask** [ludovicchabant/vim-gutentags#61] opened 2016-01-28 21:00 UTC
My disk was unexpectedly full, and after a few minutes of deleting old log files and such, realized that it was actually due to a 75gb tags temp file in /usr/local.

I suspect that it was because I opened an nginx config file earlier today, since `/etc/nginx` is symlinked to `/usr/local/etc/nginx` when installed with homebrew on OS X, and /usr/local contains a `.git` directory.

**Comment by emptyflask** [comment] 2016-01-28 21:59
Confirmed. I was able to duplicate this by opening files in /etc/nginx.

For now, this is solved with a `touch /usr/local/.notags`, but there should be some kind of sanity check before generating a ridiculously large tags index, or kill the background process if it reaches a certain threshold.

**Comment by ludovicchabant** [comment] 2016-02-21 03:17
Ah yeah, interesting. I don't know how to abort a process like this, though -- at least not from a simple shell/cmd.exe script. I could potentially put something to check for tags files growing too big while the user is idle (`CursorHold`) but this could take a while if you're busy...

**Comment by Coacher** [comment] 2016-02-22 07:02
Hello.

`ulimit [-f]` could help here. `ulimit [-f]` is [POSIX-compatible](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/ulimit.html). See [here](http://hyperpolyglot.org/unix-shells#process-job-control) for availability.

tcsh doesn't have it, but provides [limit](http://www.tcsh.org/tcsh.html/Builtin_commands.html#limit) instead. `limit` uses 1024 bytes per block and doesn't have `-f` option, you have to specify `filesize` instead.

**Comment by marcaddeo** [comment] 2016-04-01 14:01
I have a similar problem with a project I work on. I've seen it create 300GB tag files and slow my computer down considerably. Even when I don't have vim open, the rogue ctags process(es) kill the performance on my computer and continue generating GIANT ctag files.

I'm not sure if there are some symlinks pointing to eachother or something that is causing it. But it's quite annoying. I believe it's only when I'm using gutentags, as well. I believe at one point I tried disabling gutentags and using ctags manually. But that didn't really last long because I never remembered to do it.

I'll need to look into it more, but would love to hear if anyone has any suggestions.

**Comment by emptyflask** [comment] 2016-04-01 15:21
It becomes problematic on large node.js projects as well, since a lot of dependencies end up in the project directory. Again, the best solution right now is to create a `.notags` file so the directory is ignored.

**Comment by ludovicchabant** [comment] 2016-04-06 05:24
Thanks everyone for the comments so far!

So I went with a lame but practical solution for now. I added a `g:gutentags_exclude_project_root` setting that's a list of project roots you want to exclude. As mentioned here it's basically the same as putting a `.notags` file in each of those, but sometimes that's not feasible or desired. For now the setting defaults to `['/usr/local']` but we can add other default things later (I don't know if macports or chocolatey or whatever also do shenanigans like homebrew). Of course, you can override it.

Doing some monitoring on the size of the tag file doesn't seem like a good solution for me. First, there's no good portable way to do that. Second, it requires to have a _second_ script or job or whatever to monitor what the _first_ one is doing... and then you need something to handle whenever that second script is stuck or is misbehaving. I want less scripts, not more :)

The other problems mentioned here, though, are only vaguely related to Gutentags. A project with symbolic links or many dependencies inside it will generate huge tag files either way -- regardless of whether Gutentags was the one launching `ctags` or not. I myself added common dependency folders to an exclude list in my `~/.ctags`... stuff like `node_modules` and `bower_components` for instance.

I'll close this for now, but feel free to keep commenting if you have better suggestions!

**Closed by ludovicchabant** 2016-04-06 05:24 UTC

**Comment by begin29** [comment] 2019-10-03 07:45
it still creates huge tag file and feel all hard disk memory as it founds =)
Filling disk space was done during `sort -u tags` operation.
Reproducible for linux and for mac. Opened the same project folder on both envs. 
There needs some size restrictions and support for .gitignore by default if it is not done yet.

It seems node_modules, tmp folder tagged. Can't actually figured out because disk was full. After killing the process, guttentags initializes removing tags.
