### ISSUE TITLE
gutentags: ctags job failed, returned: 122

### ISSUE THREAD

**Issue by maxtcy** [ludovicchabant/vim-gutentags#189] opened 2018-06-01 15:52 UTC
Hi All, 

How to fix Permission denied error ?

"update_tags.sh" 148L, 4087C
gutentags: Scanning buffer 'update_tags.sh' for gutentags setup...
gutentags: No specific project type.
gutentags: Setting gutentags for buffer 'update_tags.sh'
gutentags: Generating missing tags file: /proj/.vim/plugged/vim-gutentags/plat/unix/.cache/tags
/proj--.vim-plugged-vim-gutentags-.tags
gutentags: Running: ['/proj/.vim/plugged/vim-gutentags/plat/unix/update_tags.sh', '-e', 'ctags'
, '-t', '/proj//.vim/plugged/vim-gutentags/plat/unix/.cache/tags/proj--.vim-plugged-vim-
gutentags-.tags', '-p', '/proj//.vim/plugged/vim-gutentags', '-o', '/proj/.vim/plugged/
vim-gutentags/res/ctags_recursive.options', '-O', '--fields=+niazS --extra=+q --c++-kinds=+px --c-kinds=
+px --output-format=e-ctags', '-l', '/proj/.vim/plugged/vim-gutentags/plat/unix/.cache/tags/pro
j--.vim-plugged-vim-gutentags-.tags.log']
gutentags: In:      /proj//.vim/plugged/vim-gutentags
gutentags: executing job failed: Permission denied
gutentags: Finished ctags job.
gutentags: gutentags: ctags job failed, returned: 122

Anyone can help me ?

**Comment by ludovicchabant** [comment] 2018-06-09 17:48
Hi!

The one thing that jumps at me is that it's running the background job from inside `proj//.vim/plugged/vim-gutentags`, and that double slash character looks suspicious...

Can you check, in that buffer, what the value of `b:gutentags_root` is (and if it has that double slash?).
AFAIK the project root finder in Gutentags should return a "clean" path, but maybe there's a bug in there... unless you're customizing that step with `g:gutentags_project_root_finder`?

**Comment by ovisan** [comment] 2019-01-25 12:56
@maxtcy
1. Try running the command manually first maybe you have a permission problem right there. In my case the file `update_tags.sh` had only read/write rights on my user, so fixed that with `chmod + x update_tags.sh`
2. you have an output there, so make sure that you have write rights there. I suggest running the command separately, first just the `update_tags.sh` without any arguments, then try the command with all the arguments.
Also like @ludovicchabant said, that `//` looks suspicious. Hope it helps.

**Comment by ovisan** [comment] 2019-01-25 13:05
@ludovicchabant fyi, using Mackup or something similar, it creates soft links for `.vim`, so `update_tags.sh` tries to open from iCloud/Dropbox/Drive or whatever storage instead to open from local `.vim`
That also is causing errors.

**Comment by mbrevda** [comment] 2019-02-18 14:54
Seems `$CTAGS_ARGS` should be quoted before being used?

```diff
--- update_tags.sh	2019-02-18 16:53:11.000000000 +0200
+++ update_tags.sh	2019-02-18 16:52:50.000000000 +0200
@@ -127,11 +127,11 @@

     echo "Running ctags on whole project"
     echo "$CTAGS_EXE -f \"$TAGS_FILE.temp\" $CTAGS_ARGS"
-    $CTAGS_EXE -f "$TAGS_FILE.temp" $CTAGS_ARGS
+    $CTAGS_EXE -f "$TAGS_FILE.temp" "$CTAGS_ARGS"
 else
     echo "Running ctags on \"$UPDATED_SOURCE\""
-    echo "$CTAGS_EXE -f \"$TAGS_FILE.temp\" $CTAGS_ARGS --append \"$UPDATED_SOURCE\""
-    $CTAGS_EXE -f "$TAGS_FILE.temp" $CTAGS_ARGS --append "$UPDATED_SOURCE"
+    echo "$CTAGS_EXE -f \"$TAGS_FILE.temp\" "$CTAGS_ARGS" --append \"$UPDATED_SOURCE\""
+    $CTAGS_EXE -f "$TAGS_FILE.temp" "$CTAGS_ARGS" --append "$UPDATED_SOURCE"
 fi

 if [ "$POST_PROCESS_CMD" != "" ]; then
```

**Comment by ludovicchabant** [comment] 2019-03-13 02:57
Ah there's already an issue about `ctags` option files with spaces in their path causing trouble. The problem is that quoting `CTAGS_ARGS` won't work because there are multiple options in there.

Closing as duplicate of #193.

**Closed by ludovicchabant** 2019-03-13 02:57 UTC

**Comment by mbrevda** [comment] 2019-03-13 06:23
Seems totally be working when quoted here

**Comment by ludovicchabant** [comment] 2019-03-13 06:33
Are you sure? Set `g:gutentags_trace` to `1` and paste the output? What platform are you on, and what shell are you using?

For me, it treats the entire arguments string as one big argument -- and understandably fails to do anything with it.

**Comment by mbrevda** [comment] 2019-03-31 09:49
Os X, bash: `gutentags: Running: ['XXXX/vim/bundle/vim-gutentags/plat/unix/update_tags.sh', '-e', 'ctags', '-t', 'tags', '-p', '.', '-s', 'src/index.test.js', '-o
', 'XXXX/vim/bundle/vim-gutentags/res/ctags_recursive.options', '-l', 'tags.log']`

**Comment by ludovicchabant** [comment] 2019-04-21 00:22
What about the contents of that `tags.log` file?
